
package org.gp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GlobalServiceManagementCallBack", targetNamespace = "http://globalplatform.org/globalservicemanagement")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GlobalServiceManagementCallBack {


    /**
     * 
     * @param deployServiceResponse
     */
    @WebMethod(operationName = "DeployService")
    @Oneway
    public void deployService(
        @WebParam(name = "DeployServiceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "DeployServiceResponse")
        DeployServiceResponseType deployServiceResponse);

    /**
     * 
     * @param upgradeServiceResponse
     */
    @WebMethod(operationName = "UpgradeService")
    @Oneway
    public void upgradeService(
        @WebParam(name = "UpgradeServiceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "UpgradeServiceResponse")
        UpgradeServiceResponseType upgradeServiceResponse);

    /**
     * 
     * @param exchangeServiceDataResponse
     */
    @WebMethod(operationName = "ExchangeServiceData")
    @Oneway
    public void exchangeServiceData(
        @WebParam(name = "ExchangeServiceDataResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "ExchangeServiceDataResponse")
        ExchangeServiceDataResponseType exchangeServiceDataResponse);

    /**
     * 
     * @param suspendOrResumeServiceResponse
     */
    @WebMethod(operationName = "SuspendOrResumeService")
    @Oneway
    public void suspendOrResumeService(
        @WebParam(name = "SuspendOrResumeServiceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "SuspendOrResumeServiceResponse")
        SuspendOrResumeServiceResponseType suspendOrResumeServiceResponse);

    /**
     * 
     * @param terminateServiceResponse
     */
    @WebMethod(operationName = "TerminateService")
    @Oneway
    public void terminateService(
        @WebParam(name = "TerminateServiceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "TerminateServiceResponse")
        TerminateServiceResponseType terminateServiceResponse);

}
