
package org.gp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GlobalServiceManagementService", targetNamespace = "http://globalplatform.org/globalservicemanagement", wsdlLocation = "file:/C:/workspaces/sts-3.6/samplews/src/main/resources/gp/wsdl/GlobalServiceManagement.wsdl")
public class GlobalServiceManagementService
    extends Service
{

    private final static URL GLOBALSERVICEMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GLOBALSERVICEMANAGEMENTSERVICE_EXCEPTION;
    private final static QName GLOBALSERVICEMANAGEMENTSERVICE_QNAME = new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/workspaces/sts-3.6/samplews/src/main/resources/gp/wsdl/GlobalServiceManagement.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GLOBALSERVICEMANAGEMENTSERVICE_WSDL_LOCATION = url;
        GLOBALSERVICEMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public GlobalServiceManagementService() {
        super(__getWsdlLocation(), GLOBALSERVICEMANAGEMENTSERVICE_QNAME);
    }

    public GlobalServiceManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns GlobalServiceManagement
     */
    @WebEndpoint(name = "GlobalServiceManagementEndPoint")
    public GlobalServiceManagement getGlobalServiceManagementEndPoint() {
        return super.getPort(new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementEndPoint"), GlobalServiceManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GlobalServiceManagement
     */
    @WebEndpoint(name = "GlobalServiceManagementEndPoint")
    public GlobalServiceManagement getGlobalServiceManagementEndPoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementEndPoint"), GlobalServiceManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GLOBALSERVICEMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw GLOBALSERVICEMANAGEMENTSERVICE_EXCEPTION;
        }
        return GLOBALSERVICEMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
