
package org.gp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GlobalServiceManagementCallBackService", targetNamespace = "http://globalplatform.org/globalservicemanagement", wsdlLocation = "file:/C:/workspaces/sts-3.6/samplews/src/main/resources/gp/wsdl/GlobalServiceManagementCallBack.wsdl")
public class GlobalServiceManagementCallBackService
    extends Service
{

    private final static URL GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_EXCEPTION;
    private final static QName GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_QNAME = new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementCallBackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/workspaces/sts-3.6/samplews/src/main/resources/gp/wsdl/GlobalServiceManagementCallBack.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_WSDL_LOCATION = url;
        GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_EXCEPTION = e;
    }

    public GlobalServiceManagementCallBackService() {
        super(__getWsdlLocation(), GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_QNAME);
    }

    public GlobalServiceManagementCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns GlobalServiceManagementCallBack
     */
    @WebEndpoint(name = "GlobalServiceManagementEndPoint")
    public GlobalServiceManagementCallBack getGlobalServiceManagementEndPoint() {
        return super.getPort(new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementEndPoint"), GlobalServiceManagementCallBack.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GlobalServiceManagementCallBack
     */
    @WebEndpoint(name = "GlobalServiceManagementEndPoint")
    public GlobalServiceManagementCallBack getGlobalServiceManagementEndPoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://globalplatform.org/globalservicemanagement", "GlobalServiceManagementEndPoint"), GlobalServiceManagementCallBack.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_EXCEPTION!= null) {
            throw GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_EXCEPTION;
        }
        return GLOBALSERVICEMANAGEMENTCALLBACKSERVICE_WSDL_LOCATION;
    }

}
