
package org.gp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GlobalServiceManagement", targetNamespace = "http://globalplatform.org/globalservicemanagement")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GlobalServiceManagement {


    /**
     * 
     * @param lookupServiceInstanceReferenceRequest
     * @return
     *     returns org.gp.LookupServiceInstanceReferenceResponseType
     */
    @WebMethod(operationName = "LookupServiceInstanceReference")
    @WebResult(name = "LookupServiceInstanceReferenceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "LookupServiceInstanceReferenceResponse")
    public LookupServiceInstanceReferenceResponseType lookupServiceInstanceReference(
        @WebParam(name = "LookupServiceInstanceReferenceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "LookupServiceInstanceReferenceRequest")
        LookupServiceInstanceReferenceRequestType lookupServiceInstanceReferenceRequest);

    /**
     * 
     * @param declareServiceInstanceReferenceRequest
     * @return
     *     returns org.gp.DeclareServiceInstanceReferenceResponseType
     */
    @WebMethod(operationName = "DeclareServiceInstanceReference")
    @WebResult(name = "DeclareServiceInstanceReferenceResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "DeclareServiceInstanceReferenceResponse")
    public DeclareServiceInstanceReferenceResponseType declareServiceInstanceReference(
        @WebParam(name = "DeclareServiceInstanceReferenceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "DeclareServiceInstanceReferenceRequest")
        DeclareServiceInstanceReferenceRequestType declareServiceInstanceReferenceRequest);

    /**
     * 
     * @param getServiceInstanceReferenceDescriptorRequest
     * @return
     *     returns org.gp.GetServiceInstanceReferenceDescriptorResponseType
     */
    @WebMethod(operationName = "GetServiceInstanceReferenceDescriptor")
    @WebResult(name = "GetServiceInstanceReferenceDescriptorResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "GetServiceInstanceReferenceDescriptorResponse")
    public GetServiceInstanceReferenceDescriptorResponseType getServiceInstanceReferenceDescriptor(
        @WebParam(name = "GetServiceInstanceReferenceDescriptorRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "GetServiceInstanceReferenceDescriptorRequest")
        GetServiceInstanceReferenceDescriptorRequestType getServiceInstanceReferenceDescriptorRequest);

    /**
     * 
     * @param getServiceStateRequest
     * @return
     *     returns org.gp.GetServiceStateResponseType
     */
    @WebMethod(operationName = "GetServiceState")
    @WebResult(name = "GetServiceStateResponse", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "GetServiceStateResponse")
    public GetServiceStateResponseType getServiceState(
        @WebParam(name = "GetServiceStateRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "GetServiceStateRequest")
        GetServiceStateRequestType getServiceStateRequest);

    /**
     * 
     * @param deployServiceRequest
     */
    @WebMethod(operationName = "DeployService")
    @Oneway
    public void deployService(
        @WebParam(name = "DeployServiceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "DeployServiceRequest")
        DeployServiceRequestType deployServiceRequest);

    /**
     * 
     * @param upgradeServiceRequest
     */
    @WebMethod(operationName = "UpgradeService")
    @Oneway
    public void upgradeService(
        @WebParam(name = "UpgradeServiceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "UpgradeServiceRequest")
        UpgradeServiceRequestType upgradeServiceRequest);

    /**
     * 
     * @param exchangeServiceDataRequest
     */
    @WebMethod(operationName = "ExchangeServiceData")
    @Oneway
    public void exchangeServiceData(
        @WebParam(name = "ExchangeServiceDataRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "ExchangeServiceDataRequest")
        ExchangeServiceDataRequestType exchangeServiceDataRequest);

    /**
     * 
     * @param suspendOrResumeServiceRequest
     */
    @WebMethod(operationName = "SuspendOrResumeService")
    @Oneway
    public void suspendOrResumeService(
        @WebParam(name = "SuspendOrResumeServiceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "SuspendOrResumeServiceRequest")
        SuspendOrResumeServiceRequestType suspendOrResumeServiceRequest);

    /**
     * 
     * @param terminateServiceRequest
     */
    @WebMethod(operationName = "TerminateService")
    @Oneway
    public void terminateService(
        @WebParam(name = "TerminateServiceRequest", targetNamespace = "http://namespaces.globalplatform.org/systems-messaging/2.1.0", partName = "TerminateServiceRequest")
        TerminateServiceRequestType terminateServiceRequest);

}
